spring:
  cloud:
    openfeign:
      client:
        config:
          resource-server:
            url: http://localhost:8081
          payment-server:
            url: http://localhost:8082

api:
  basic-uri:
    resource-server: http://localhost:8081
    payment-server: http://localhost:8082

tmpVar: configServer