eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8085/eureka}
  instance:
    preferIpAddress: true

api:
  basic-uri:
    resource: http://localhost:8081
    payment: http://localhost:8082